### ISSUE TITLE
确实文件

### ISSUE THREAD

**Issue by JoYanceS** [wdragondragon/apex-yolov5#8]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

AssertionError: File not found: .\apex_model\1w2\1w.yaml
为什么我没有这个权重文件

**Comment by wdragondragon** [comment]
The files under the apex_model folder are pt or engine and yaml configuration files that need to train your own model. These files are not open source, and you can leave your mailbox if you really need them.

apex_model 文件夹下的文件是需要自己训练模型的pt或engine和yaml配置文件，这些文件并没有开源，如果你实在需要，可以留下你的邮箱。

**Comment by JoYanceS** [comment]
我的邮箱是：
1937727366@qq.com
如果这个不行的话麻烦你可以试试这个：
19956340321@163.com
My email address is:
1937727366@qq.com
If this doesn't work, please try this:
19956340321@163.com
Thank you very much

**Comment by wdragondragon** [comment]
The weight file has been sent to your email.

已经发送权重文件到你的邮箱。

**Comment by jjjhhhjhb** [comment]
能吧权重文件发给我的邮箱吗谢谢啦
3435407671@qq.com
qqq3435407671@gmail.com

**Comment by YouKnowMyEggs** [comment]
459779764@qq.com
youknowmyeggs@gmail.com
求一份权重文件，谢谢！已Star
